mod 'puppetlabs-stdlib', ' 6.1.0'
mod 'puppetlabs-translate', ' 2.0.0'
mod 'puppet-cron', ' 1.3.1'
mod 'puppetlabs-scheduled_task', ' 2.0'
mod 'puppetlabs-cron_core', ' 1.0.3'
mod 'albatrossflavour-os_patching', '0.13.0'
